changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
      - wontfix
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
        - major
    - title: New Features
      labels:
        - enhancement
        - feature
        - new
    - title: Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Dependencies
      labels:
        - dependencies
        - deps
    - title: Other Changes
      labels:
        - "*"
